service: developer-jobs-proxy

provider:
  name: aws
  runtime: nodejs8.10

custom:
  environment: ${file(env.yml):default}

functions:
  search:
    handler: handler.search
    environment:
      reedAPIKey: ${self:custom.environment.REED_API_KEY}
    events:
      - http:
          path: search
          method: get
          cors: true